#----------------------------------------------------------------------
#           GLOBAL MAKEFILE
#----------------------------------------------------------------------

# Local settings (optional)
# WARNING: do not commit to a repository!
-include Makefile.local

# Eliom settings
include Makefile.options

# Eliom-base-app makefile
include Makefile.eba

# Project specific makefile
include Makefile.$(PROJECT_NAME)

# Mobile app makefile
include Makefile.mobile
