#----------------------------------------------------------------------
#           SETTINGS FOR THE ELIOM PROJECT %%%PROJECT_NAME%%%
#----------------------------------------------------------------------

## Here you can add specific rules for your project. It's recommended to add
## variables in Makefile.options (which is supposed to contain all variables and
## no rules).

## This file is included in Makefile.os. You can also use any variable defined
## in Makefile.options.
