;
; This Dune file was generated with ocsigen-dune-rules.
; To update it, modify the invocation below and run
;
;     dune runtest --auto-promote
;

(rule
 (with-stdout-to
  dune.corrected
  (run
   ocsigen-dune-rules
   gen-library
   --public-name
   ocsigen-start
   ocsigen_start
   --preprocess
   js_of_ocaml-ppx_deriving_json
   --no-rpc-raw
   --libraries
   calendar,re.str
   --server-libraries
   safepass,yojson,cohttp-lwt-unix,pgocaml,resource-pooling
   --eliom-libraries
   ocsigen-toolkit)))

;
; Below this line, any changes will be overwritten.
;

(rule
 (alias runtest)
 (action
  (diff dune dune.corrected)))

(library
 (public_name ocsigen-start.server)
 (name ocsigen_start)
 (modes byte native)
 (wrapped false)
 (library_flags
  (:standard -linkall))
 (preprocess
  (pps eliom.ppx.server ocsigen-ppx-rpc js_of_ocaml-ppx_deriving_json))
 (libraries
  eliom.server
  safepass
  yojson
  cohttp-lwt-unix
  pgocaml
  resource-pooling
  calendar
  re.str
  ocsigen-toolkit.server))

(subdir
 client
 (library
  (public_name ocsigen-start.client)
  (name ocsigen_start)
  (modes byte)
  (wrapped false)
  (library_flags
   (:standard -linkall))
  (preprocess
   (pps js_of_ocaml-ppx js_of_ocaml-ppx_deriving_json))
  (libraries
   eliom.client
   js_of_ocaml
   js_of_ocaml-lwt
   calendar
   re.str
   ocsigen-toolkit.client))
 (dynamic_include ../dune.client))

(rule
 (deps
  (glob_files *.eliom)
  (glob_files *.eliomi))
 (action
  (with-stdout-to
   dune.client
   (run ocsigen-dune-rules gen-client-modules .))))
